### ISSUE TITLE
What's the intended usecase for AppBlocks?

### ISSUE THREAD

**Issue by LrWm3** [AGTGreg/AppBlocks#1]
hello.

I saw you had shared this lib on r/JavascriptFrameworks. I read the README as well as that this was inspired by Vue and Blaze in your Reddit post.

however, it's unclear when AppBlocks would be a good choice over something like Vue, Blaze, React + Reduz, Angular, etc, from your description.

the two main features I took away were it's small and it is easy to use.

If the main use case for appblocks is for developing low memory footprint frontends, it might be nice to compare its minified size to other frameworks.

it is hard for me to imagine it being easier to use than those other frontend frameworks I mentioned. but if that is also part of the idea it might be nice to compare how operations are performed in say, vue, to how they are performed in AppBlocks. Maybe if there are a few types of frontends where AppBlicks is a really good fit, those could be mentioned, as well as applications where other options might be better.

cool project btw.

**Comment by AGTGreg** [comment]
Hello LrWm3,

You make excellent points here. The use case for AppBlocks is for developing low memory footprint frontends as you put it. And also, it is very easy to integrate to any project.

We needed a way to develop front-end applications rapidly and with minimum code writing for our existing websites and applications without changing much of the codebase.

The ideal library would be able to be loaded as a script tag (npm is optional), provide template syntax, be fast, low footprint and cover the most common use cases we encounter in our day to day tasks. 

While Vue is certainly a good choice for that since it is a progressive library and can be loaded as a script tag, AppBlocks is significantly smaller in size while covering the most common use cases when developing front-end applications.

Here's a quick comparison of the size with other javascript libraries / frameworks from https://cost-of-modules.herokuapp.com/
Name | Size
-- | --
Vue 2.6.11 | 63.5kB
react-dom 16.13.1 | 114.6kB
angular 1.7.9 | 179.5kB
inferno 7.4.2 | 21.2kB
preact 10.4.1 | 9.8kB
**AppBlocks 1.2.2** | 4.5kB

I will add a comparison section in the documentation. Thank you for pointing this out.

**Comment by AGTGreg** [comment]
50d4a473ac8105ee76afce243447e76769c27cc0

**Comment by AGTGreg** [comment]
Added here: https://agtgreg.github.io/AppBlocks/#/whyappblocks :)

Commit 50d4a473ac8105ee76afce243447e76769c27cc0

**Comment by LrWm3** [comment]
Just wanted to say I think you did a great job articulating AppBlocks usecases.
